pipeline:
  docker:
    image: plugins/docker
    repo: leonidas/wordpress
    secrets: [docker_username, docker_password]
    tag: latest
    when:
      branch: master
      event: [push]

  deploy:
    image: leonidas/kontenacli
    commands:
      - /docker_entrypoint.sh stack upgrade --deploy hokister kontena.yml
    secrets: [master_name, master_url, grid_name, access_token]
    when:
      branch: master
      event: [push]
